In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

### Ejercicio 1. 

Escribir un programa que implemente el metodo de Jacobi y otro que implemente el metodo de Gauss-Seidel para la resolucion de un sistema lineal Ax = b, con las siguientes
condiciones:
* que finalice si el metodo se estaciona,
* que finalice con una advertencia si se excede cierto tope de iteraciones.

Sugerencia: investigar los comandos np. tril , np. triu y np.diag.

In [10]:
def jacobi(A):
    D = np.diag(A)
    L = np.tril(A)
    U = np.triu(A)
    
    return D, L, U

A = np.arange(1,10).reshape(3,3)
D, L, U = jacobi(A)

In [11]:
D

array([1, 5, 9])

In [6]:
L

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [7]:
U

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])